### ISSUE TITLE
Dragonberry

### ISSUE THREAD

**Issue by faddat** [joe-chain/joe#9]
FYI, #8 is a state breaking change, maybe.  It might be able to be applied smoothly without state breaks.  

1/3rd of vp should apply ASAP, which will cause the chain to halt in the event that it is attacked.

Once 2/3rd of VP has it, then the chain wouldn't halt in that case 

Release notes for v0.46.6 are here:

https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.6

**Comment by reecepbcups** [comment]
I have another tokenfactory state breaking patch that I need to push out so I'll push it through at the same time thx

Have to figure out how to software upgrade proposal & work with vals to vote in a 6 hour window :D
